version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the Java project...
      - mvn package -DskipTests

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
