version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
